name: Tarragon Web Scrap

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  run-webscrap:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # caching pip dependencies automáticamente

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Informe Recomendacion Semanal
        run: python -u informesemanal_runner.py

      - name: Commit and push database changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add database/riego.db
          git commit -m "Update riego.db [skip ci]" || echo "No changes to commit"
          git pull --rebase origin master
          git push
