name: Tarragon Web Scrap

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  setup-db:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r riego/requirements.txt

      - name: Create database
        run: python riego/database/create_db.py

  run-webscrap:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      DB_PATH: database/riego.db
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r riego/requirements.txt

      - name: Run webscrapBD.py
        run: python riego/webscrapBD.py
